name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.vdeleon11}}
        DOCKER_PASSWORD: ${{secrets.Jzxka81fg}}
      run: |
        docker login -u $vdeleon11 -p $Jzxka81fg
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vdeleon11/cmpsc90dadockerimage:$(date +%s)
      
    - name: Docker push
      run: docker push ${{secrets.vdeleon11}}/cmpsc90dadockerimage
